Repository astropy/pyvo, pull requests merged in 2021-04, with the labels that each got.

#260 Fixed wrong tox targets
  .github/workflows/cibuild.yml
  tox.ini
Labels: bug, no-changelog-entry-needed

#241 Make datalink .bysemantics semantics-aware
  CHANGES.rst
  pyvo/dal/adhoc.py
  pyvo/dal/tests/data/datalink/proc.xml
  pyvo/dal/tests/test_datalink.py
  pyvo/utils/tests/test_vocabularies_remote.py
  pyvo/utils/vocabularies.py
Labels: enhancement

#261 MNT: Do not write config on import
  pyvo/_astropy_init.py
  pyvo/pyvo.cfg
Labels: no-changelog-entry-needed
