Repository astropy/pyvo, pull requests merged in 2022-09, with the labels that each got.

#353 CI: use nightly wheels
  .github/workflows/cibuild.yml
  README.rst
  pyvo/__init__.py
  pyvo/conftest.py
  pyvo/dal/tests/test_mimetype.py
  setup.cfg
  tox.ini
Labels: no-changelog-entry-needed, infrastructure

#357 Canonicalize case of TAP query parameter id
  CHANGES.rst
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
Labels: bug

#363 Changing registry/index.rst example to use short names.
  docs/registry/index.rst
Labels: no-changelog-entry-needed, documentation

#358 CI: adding remote-data test job, remove duplicate
  .github/workflows/cibuild.yml
  conftest.py
  docs/dal/index.rst
  docs/index.rst
  docs/registry/index.rst
  pyvo/dal/adhoc.py
  pyvo/dal/sia.py
  pyvo/dal/ssa.py
  pyvo/dal/tests/test_sia2_remote.py
  pyvo/registry/tests/test_regtap.py
  tox.ini
Labels: no-changelog-entry-needed, infrastructure

#362 MAINT: remove marker for passing xfails
  pyvo/dal/tests/test_query.py
Labels: no-changelog-entry-needed

#364 MAINT: cleanup astropy <4.1 code
  pyvo/dal/adhoc.py
  pyvo/dal/tests/test_datalink.py
  pyvo/dal/tests/test_query.py
  pyvo/utils/compat.py
Labels: no-changelog-entry-needed

#355 Better exception
  CHANGES.rst
  pyvo/dal/adhoc.py
  pyvo/dal/exceptions.py
  pyvo/dal/query.py
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
Labels: bug

#274 Support for TAP table create/delete/upload CADC prototype
  CHANGES.rst
  docs/dal/index.rst
  docs/prototypes/index.rst
  pyvo/auth/authsession.py
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
  pyvo/utils/protofeature.py
  pyvo/utils/prototype.py
Labels: enhancement
