Repository astropy/pyvo, pull requests merged in 2022-11, with the labels that each got.

#383 MAINT: minor typo fix
  pyvo/dal/query.py
Labels: no-changelog-entry-needed

#371 MAINT: minor fixes to setup.cfg and MANIFEST
  MANIFEST.in
  pyvo/dal/adhoc.py
  pyvo/dal/dbapi2.py
  pyvo/dal/params.py
  pyvo/dal/query.py
  pyvo/dal/sia2.py
  pyvo/dal/tests/test_adhoc.py
  pyvo/dal/tests/test_datalink.py
  pyvo/dal/tests/test_mimetype.py
  pyvo/dal/tests/test_params.py
  pyvo/dal/tests/test_sia2.py
  pyvo/dal/tests/test_sia2_remote.py
  pyvo/dal/tests/test_tap.py
  pyvo/io/vosi/exceptions.py
  pyvo/io/vosi/tests/test_capabilities.py
  pyvo/io/vosi/tests/test_tables.py
  pyvo/io/vosi/vodataservice.py
  pyvo/registry/regtap.py
  pyvo/registry/rtcons.py
  pyvo/registry/tests/commonfixtures.py
  pyvo/registry/tests/test_regtap.py
  pyvo/registry/tests/test_rtcons.py
  pyvo/samp.py
  pyvo/utils/formatting.py
  pyvo/utils/protofeature.py
  pyvo/utils/prototype.py
  pyvo/utils/tests/test_http.py
  pyvo/utils/tests/test_prototype.py
  pyvo/utils/tests/test_vocabularies_remote.py
  pyvo/utils/vocabularies.py
  pyvo/utils/xml/elements.py
  pyvo/utils/xml/tests/test_elements.py
  setup.cfg
  tox.ini
Labels: no-changelog-entry-needed, infrastructure

#372 DOC: Change link targets at the protocol overview into pyVO docs; add brief intro for each service protocol
  docs/dal/index.rst
  docs/index.rst
Labels: no-changelog-entry-needed, documentation

#385 Removed use of deprecated cgi module
  pyvo/dal/mimetype.py
  pyvo/dal/query.py
  pyvo/dal/tests/test_sia2_remote.py
  pyvo/utils/formatting.py
Labels: bug, no-changelog-entry-needed
