Repository astropy/pyvo, pull requests merged in 2023-07, with the labels that each got.

#452 ENH: adding sys.version to User-Agent
  CHANGES.rst
  pyvo/dal/tests/test_query.py
  pyvo/utils/http.py
  pyvo/utils/tests/test_http.py
Labels: enhancement

#455 DOC: change ssa url
  docs/dal/index.rst
Labels: no-changelog-entry-needed, documentation

#436 DOC: Improvements on doc for TAP service and other minor changes
  docs/dal/index.rst
  pyvo/dal/query.py
  pyvo/dal/tap.py
Labels: no-changelog-entry-needed, documentation

#457 DOC: fix dal doctest failure
  docs/dal/index.rst
  setup.cfg
Labels: infrastructure, documentation

#461 CI: adding changelog checking GHA
  .github/workflows/changelog.yml
  pyproject.toml
Labels: no-changelog-entry-needed

#462 TST: restructure tests to use parametrize rather than internal loop
  pyvo/dal/tests/test_sia2.py
Labels: no-changelog-entry-needed

#426 ENH: Add more text to registry.search docstring for the types of constraints that can be used
  pyvo/registry/regtap.py
Labels: no-changelog-entry-needed, documentation, component: registry

#465 MAINT: add workaround for doctesting with new numpy repr
  pyvo/conftest.py
Labels: no-changelog-entry-needed, infrastructure

#463 BUG: fix handling of nan input for Time properties
  CHANGES.rst
  pyvo/dal/sia2.py
Labels: bug, component: SIA

#459 BUG: SIA2 position search to be SkyCoord aware
  CHANGES.rst
  pyvo/dal/params.py
  pyvo/dal/tests/test_sia.py
  pyvo/dal/tests/test_sia2.py
Labels: bug, component: SIA

#443 DOC: Integrate the content of the "/examples" directory into docs [Issue #396]
  docs/dal/index.rst
  docs/registry/index.rst
  examples/auth/cadc_auth_example.py
  examples/auth/cert_auth_example.py
  examples/auth/gaia_auth_example.py
  examples/images/README.rst
  examples/images/ex_casA_image_cat.py
  examples/images/ex_get_cutouts.py
  examples/notebooks/simple_service_discovery.ipynb
  examples/notebooks/working_with_registry_results.ipynb
  examples/serialquery.py
Labels: no-changelog-entry-needed, documentation
