Repository astropy/pyvo, pull requests merged in 2023-08, with the labels that each got.

#467 MAINT: no automated black formatting here
  pyproject.toml
Labels: no-changelog-entry-needed, infrastructure

#468 MAINT: fix formatting raised by new flake8 version
  pyvo/dal/mimetype.py
  pyvo/dal/query.py
  pyvo/dal/sia.py
  pyvo/dal/sia2.py
  pyvo/dal/ssa.py
  pyvo/dal/tests/test_params.py
  pyvo/dal/tests/test_query.py
  pyvo/dal/tests/test_tap.py
  pyvo/io/vosi/tests/test_capabilities.py
  pyvo/io/vosi/tests/test_tables.py
Labels: no-changelog-entry-needed

#445 BUG: SIA1's getdataurl() to favour ``VOX:Image_AccessReference``
  CHANGES.rst
  pyvo/dal/sia.py
  pyvo/dal/tests/data/sia/dataset.xml
Labels: bug, component: SIA

#472 MAINT: remove unused top-level tests directory
  pyvo/tests/__init__.py
Labels: no-changelog-entry-needed, infrastructure

#474 CI: reorg workflows; fix RTD versioning; fix dev version installs
  .github/workflows/ci_devtests.yml
  .github/workflows/ci_tests.yml
  .readthedocs.yml
  tox.ini
Labels: no-changelog-entry-needed, infrastructure

#481 BUG: fix numpy dev version as their versioning system changed
  pyvo/conftest.py
Labels: bug, no-changelog-entry-needed

#482 Removing a remote-data mark in a RegTAP test.
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed

#485 CI: remove deprecated/removed RTD config
  .readthedocs.yml
Labels: no-changelog-entry-needed
