Repository astropy/pyvo, pull requests merged in 2023-01, with the labels that each got.

#384 Added support for QTable
  CHANGES.rst
  docs/dal/index.rst
  pyvo/dal/query.py
  pyvo/dal/tests/test_query.py
Labels: enhancement

#402 No longer discarding single untyped interfaces.
  pyvo/registry/regtap.py
  pyvo/registry/tests/test_regtap.py
Labels: bug, no-changelog-entry-needed, component: registry

#395 Fixing a query generation for the epn-tap data model.
  CHANGES.rst
  pyvo/registry/rtcons.py
  pyvo/registry/tests/test_regtap.py
  pyvo/registry/tests/test_rtcons.py
Labels: bug

#406 DOC: remove mentions of nonexisting nrecs attribute
  pyvo/dal/scs.py
  pyvo/dal/sia.py
  pyvo/dal/sia2.py
  pyvo/dal/sla.py
  pyvo/dal/tap.py
Labels: bug, no-changelog-entry-needed, documentation

#367 Remove defaults for SIAv1 query params
  CHANGES.rst
  pyvo/dal/sia.py
  pyvo/dal/ssa.py
Labels: bug, component: SIA

#410 Improving servicetype documentation
  pyvo/registry/__init__.py
  pyvo/registry/rtcons.py
Labels: no-changelog-entry-needed, documentation

#415 Make all-vo example work
  docs/index.rst
  docs/registry/index.rst
Labels: no-changelog-entry-needed, documentation

#414 MAINT: removal of unused tests directory
  tests/README.txt
  tests/testLicense.py
Labels: no-changelog-entry-needed
