Repository astropy/pyvo, pull requests merged in 2023-06, with the labels that each got.

#448 TST: Update URL for Scientific Python nightlies
  tox.ini
Labels: no-changelog-entry-needed, infrastructure

#447 Tj taprecord session
  CHANGES.rst
  pyvo/dal/tap.py
Labels: bug, component: dal

#453 MAINT: minor cleanup of old version workarounds
  pyvo/dal/tests/test_query.py
  pyvo/samp.py
Labels: no-changelog-entry-needed
