Repository astropy/pyvo, pull requests merged in 2023-12, with the labels that each got.

#501 DEP: temporarily using dev version of indirect dependency pyerfa
  tox.ini
Labels: no-changelog-entry-needed

#500 Relaxed baseurl requirements in SIA2Service
  CHANGES.rst
  pyvo/dal/sia2.py
  pyvo/dal/tests/test_sia2.py
  pyvo/dal/tests/test_sia2_remote.py
  pyvo/dal/vosi.py
  pyvo/registry/regtap.py
  pyvo/registry/tests/test_regtap.py
Labels: bug, component: SIA

#506 Make registry.Interface construction work with no standard_id.
  pyvo/registry/regtap.py
Labels: no-changelog-entry-needed

#386 ENH: Make regtap service aware
  CHANGES.rst
  docs/registry/index.rst
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
  pyvo/dal/vosi.py
  pyvo/io/vosi/exceptions.py
  pyvo/io/vosi/tapregext.py
  pyvo/registry/__init__.py
  pyvo/registry/regtap.py
  pyvo/registry/rtcons.py
  pyvo/registry/tests/commonfixtures.py
  pyvo/registry/tests/data/capabilities.xml
  pyvo/registry/tests/test_regtap.py
  pyvo/registry/tests/test_rtcons.py
  pyvo/utils/xml/tests/test_elements.py
Labels: component: registry

#508 DOC: fixing docstring error
  pyvo/dal/query.py
Labels: no-changelog-entry-needed, documentation

#509 API: fix backward compatibility in preparation for release
  pyvo/registry/rtcons.py
Labels: Affects-dev

#510 TST: update kwarg usage in tests and code to use keywords
  pyvo/auth/tests/test_auth.py
  pyvo/dal/adhoc.py
  pyvo/dal/query.py
  pyvo/dal/scs.py
  pyvo/dal/sia.py
  pyvo/dal/sla.py
  pyvo/dal/ssa.py
  pyvo/dal/tap.py
  pyvo/dal/tests/test_scs.py
  pyvo/registry/regtap.py
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed

#505 Feature: add possibility to return full list of services
  CHANGES.rst
  docs/registry/index.rst
  pyvo/dal/query.py
  pyvo/dal/scs.py
  pyvo/dal/sia.py
  pyvo/dal/sia2.py
  pyvo/dal/sla.py
  pyvo/dal/ssa.py
  pyvo/dal/tap.py
  pyvo/dal/tests/test_query.py
  pyvo/dal/tests/test_scs.py
  pyvo/dal/tests/test_sia.py
  pyvo/dal/tests/test_sla.py
  pyvo/dal/tests/test_ssa.py
  pyvo/dal/tests/test_tap.py
  pyvo/registry/regtap.py
  pyvo/registry/tests/data/multi-interface.xml
  pyvo/registry/tests/data/regtap.xml
  pyvo/registry/tests/test_regtap.py
  pyvo/registry/tests/test_rtcons.py
Labels: bug, component: registry
