Repository astropy/pyvo, pull requests merged in 2024-02, with the labels that each got.

#520 BUG: fixing maxrec=0 case for SIA2 queries
  pyvo/dal/sia2.py
Labels: bug, component: SIA

#523 Backing out of requesting alt_identifiers every time.
  CHANGES.rst
  pyvo/registry/regtap.py
  pyvo/registry/tests/test_regtap.py
  pyvo/registry/tests/test_rtcons.py
Labels: bug, component: registry

#416 DOC: Enabling nitpicky docs build
  docs/auth/index.rst
  docs/conf.py
  docs/dal/index.rst
  docs/index.rst
  docs/io/index.rst
  docs/io/uws.rst
  docs/io/vosi.rst
  docs/nitpick-exceptions
  docs/registry/index.rst
  docs/utils/index.rst
  docs/utils/prototypes.rst
  pyvo/auth/authsession.py
  pyvo/auth/authurls.py
  pyvo/dal/__init__.py
  pyvo/dal/adhoc.py
  pyvo/dal/query.py
  pyvo/dal/scs.py
  pyvo/dal/sia.py
  pyvo/dal/sia2.py
  pyvo/dal/sla.py
  pyvo/dal/ssa.py
  pyvo/dal/tap.py
  pyvo/io/uws/endpoint.py
  pyvo/io/uws/tree.py
  pyvo/io/vosi/endpoint.py
  pyvo/io/vosi/vodataservice.py
  pyvo/io/vosi/voresource.py
  pyvo/registry/__init__.py
  pyvo/registry/regtap.py
  pyvo/registry/rtcons.py
Labels: no-changelog-entry-needed

#511 MAINT: updating mailmap after v1.5
  .mailmap
Labels: no-changelog-entry-needed

#529 DOC: changelog update after 1.5.1 release
  CHANGES.rst
Labels: no-changelog-entry-needed
