Repository astropy/pyvo, pull requests merged in 2024-08, with the labels that each got.

#583 Adding `sia1` as servicetype
  CHANGES.rst
  docs/registry/index.rst
  pyvo/registry/rtcons.py
  pyvo/registry/tests/test_rtcons.py
Labels: component: registry

#449 Deprecating image and spectrum as registry servicetype-s
  CHANGES.rst
  docs/registry/index.rst
  pyvo/registry/rtcons.py
  pyvo/registry/tests/test_rtcons.py
Labels: component: registry

#585 DOC: examples have changed upstream, change index in docs
  docs/dal/index.rst
Labels: no-changelog-entry-needed, documentation

#587 DOC: fix some typos
  pyvo/dal/scs.py
  pyvo/dal/sia.py
  pyvo/dal/sla.py
  pyvo/dal/ssa.py
  pyvo/dal/tap.py
Labels: no-changelog-entry-needed, documentation

#588 MAINT: fix doctest typoes fixed upstream
  docs/registry/index.rst
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed

#590 BUG: better session handling in registry
  CHANGES.rst
  pyvo/registry/regtap.py
Labels: bug, component: registry

#589 MAINT: adding Python 3.13 to CI
  .github/workflows/ci_devtests.yml
  tox.ini
Labels: no-changelog-entry-needed
