Repository astropy/pyvo, pull requests merged in 2024-09, with the labels that each got.

#592 DOC: ignore one more job.phase
  docs/dal/index.rst
Labels: no-changelog-entry-needed, documentation

#597 CI: bump oldest numpy version in CI
  tox.ini
Labels: no-changelog-entry-needed

#600 Update repo URL
  CONTRIBUTORS.rst
  docs/index.rst
Labels: no-changelog-entry-needed

#602 Sped up sia2 remote tests
  pyvo/dal/tests/test_sia2_remote.py
Labels: no-changelog-entry-needed

#570 Avoid assuming that `access_url` exists always
  pyvo/dal/adhoc.py
Labels: bug, component: dal

#599 Fix bug #543
  CHANGES.rst
  pyvo/dal/adhoc.py
  pyvo/dal/query.py
  pyvo/dal/tests/test_datalink.py
  pyvo/utils/testing.py
Labels: bug, component: dal

#603 MNT: Use hash for Action workflow versions and update if needed
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/ci_devtests.yml
  .github/workflows/ci_tests.yml
Labels: no-changelog-entry-needed, infrastructure
