Repository astropy/pyvo, pull requests merged in 2025-03, with the labels that each got.

#657 DOC: update registry list output
  docs/registry/index.rst
Labels: no-changelog-entry-needed, documentation

#656 Update MAST alt registry links
  docs/registry/index.rst
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed, component: registry

#659 More careful NULL value handling in tapregext data limits.
  pyvo/io/vosi/tapregext.py
  pyvo/io/vosi/tests/data/capabilities/minimal-tapregext.xml
  pyvo/io/vosi/tests/test_capabilities.py
Labels: bug
