Repository astropy/pyvo, pull requests merged in 2025-01, with the labels that each got.

#638 MAINT: update URLs for gavo dc results
  docs/dal/index.rst
  docs/registry/index.rst
  pyvo/discover/tests/test_imagediscovery.py
Labels: no-changelog-entry-needed, documentation

#637 MAINT: ignoring IERS warnings
  docs/dal/index.rst
  setup.cfg
Labels: no-changelog-entry-needed, infrastructure

#636 MAINT: moving the str input validation out to avoid astropy deprecation
  pyvo/dal/params.py
  pyvo/dal/tests/test_adhoc.py
Labels: no-changelog-entry-needed, upstream

#640 Make TAP job deletion optional defaulting to True
  CHANGES.rst
  pyvo/dal/tap.py
Labels: component: dal

#643 fix: remove alternate identifier
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed, upstream

#644 Ensure AsyncTAPJob.result strictly follows TAP spec result ID requirement
  CHANGES.rst
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
Labels: component: dal
