Repository astropy/pyvo, pull requests merged in 2025-06, with the labels that each got.

#679 fix: change JobSummary (UWS) to support jobInfo elements with any XML content
  CHANGES.rst
  pyvo/io/uws/tests/data/job-with-duplicate-elements.xml
  pyvo/io/uws/tests/data/job-with-empty-jobinfo.xml
  pyvo/io/uws/tests/data/job-with-namespace-elements.xml
  pyvo/io/uws/tests/data/job-with-nested-jobinfo.xml
  pyvo/io/uws/tests/data/job-with-simple-jobinfo.xml
  pyvo/io/uws/tests/data/job-with-typed-jobinfo.xml
  pyvo/io/uws/tests/test_job.py
  pyvo/io/uws/tree.py
Labels: component: io

#681 DOC: fixing referencing syntax
  docs/mivot/annoter.rst
  docs/mivot/example.rst
Labels: no-changelog-entry-needed, documentation

#684 Fix job result handling to prioritize standard URL structure
  CHANGES.rst
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
Labels: component: dal

#682 Add documentation for docs/io/uws.rst
  docs/io/uws.rst
  pyvo/io/uws/tree.py
Labels: no-changelog-entry-needed, documentation, component: io
