Repository astropy/pyvo, pull requests merged in 2025-04, with the labels that each got.

#654 Fixed DL excessive copy
  CHANGES.rst
  docs/dal/index.rst
  pyvo/dal/adhoc.py
  pyvo/dal/tests/test_datalink.py
Labels: bug, no-changelog-entry-needed

#661 Update authenticated TAPService example
  docs/dal/index.rst
Labels: bug, no-changelog-entry-needed, documentation

#663 MAINT: post v1.6.2 consistency cleanups
  CHANGES.rst
  setup.cfg
Labels: no-changelog-entry-needed, infrastructure, documentation

#665 TST: updating tests for vizier changes
  docs/registry/index.rst
  pyvo/registry/tests/test_regtap.py
Labels: no-changelog-entry-needed, upstream

#667 fix: delete jobs when delete=True even on DALQueryErrors
  CHANGES.rst
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
Labels: bug, component: dal

#669 [Issue 668] [SIA2 service] check existence of standardid
  CHANGES.rst
  pyvo/dal/sia2.py
  pyvo/dal/tests/test_sia2.py
Labels: bug, component: SIA
