Repository astropy/pyvo, pull requests merged in 2025-02, with the labels that each got.

#646 fix: conesearch is now https
  docs/registry/index.rst
Labels: no-changelog-entry-needed

#641 More information in error message when _get_endpoint requests fail
  CHANGES.rst
  pyvo/dal/query.py
  pyvo/dal/tap.py
  pyvo/dal/tests/test_tap.py
  pyvo/dal/vosi.py
  pyvo/io/vosi/endpoint.py
Labels: component: dal

#647 MAINT: remove outdated docutils pin
  .readthedocs.yml
  docs/requirements.txt
  pyvo/io/vosi/endpoint.py
  pyvo/io/vosi/vodataservice.py
Labels: no-changelog-entry-needed, infrastructure

#648 DOC: Fixing up changelog after releasing v1.6.1
  CHANGES.rst
Labels: no-changelog-entry-needed

#653 MAINT: Corrections to some of the parameter types in the docs and a couple lint-related fixes
  pyvo/dal/adhoc.py
  pyvo/dal/exceptions.py
  pyvo/dal/query.py
  pyvo/dal/tap.py
  pyvo/dal/vosi.py
Labels: no-changelog-entry-needed

#649 Add a UAT registry constraint
  CHANGES.rst
  docs/dal/index.rst
  docs/discover/index.rst
  docs/registry/index.rst
  pyvo/registry/__init__.py
  pyvo/registry/rtcons.py
  pyvo/registry/tests/test_rtcons.py
Labels: enhancement, component: registry
